# Generated by Django 3.0.3 on 2020-04-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200402_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='object_id',
            new_name='object_uuid',
        ),
    ]
