# Generated by Django 3.0.3 on 2020-03-26 13:44

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(db_column='is_del', default=False, verbose_name='是否删除')),
                ('name', models.CharField(default='', max_length=50, verbose_name='类别名')),
                ('category_type', models.CharField(choices=[('1', '一级类目'), ('2', '二级类目')], default='', max_length=100)),
                ('parents_catrgory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_cat', to='article.ArticleCategory', verbose_name='父类目级')),
            ],
            options={
                'verbose_name': '文章类别',
                'verbose_name_plural': '文章类别',
                'db_table': 'article_category',
            },
        ),
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(db_column='is_del', default=False, verbose_name='是否删除')),
                ('article_uuid', models.UUIDField(default=uuid.uuid4, help_text='文章UUID', primary_key=True, serialize=False, verbose_name='UUID')),
                ('article_title', models.CharField(max_length=300, verbose_name='文章标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('privacy', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('read_num', models.IntegerField(default=0, verbose_name='阅读数')),
                ('recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('article_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog_user.BlogUser', verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.ArticleCategory', verbose_name='文章类别')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'article',
                'ordering': ('-create_time',),
            },
        ),
    ]
